version: '3.8'

volumes:
  supplier_service_db_pg:

services:
  supplier_service_db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: sc
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supplier_service_db
    volumes:
      - supplier_service_db_pg:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      suppliercosumer:

  supplier_service:
    container_name: supplier
    restart: always
    build: ./supplier_service
    ports:
      - "8081:8081"
    depends_on:
      - supplier_service_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://supplier_service_db:5432/supplier_service_db'
      JAVA_OPTS: '-Xmx512m'
    networks:
      suppliercosumer:

  consumer_service:
    container_name: consumer
    restart: always
    build: ./consumer_service
    ports:
      - "8080:8080"
    depends_on:
      - supplier_service
    environment:
      SERVICE: 'http://supplier:8081'
      JAVA_OPTS: '-Xmx512m'
    networks:
      suppliercosumer:
networks:
  suppliercosumer: